name: Windows

on:
  push:
    branches: [ master ]
    paths: [ '.github/workflows/windows.yml', 'windows/**' ]
  pull_request:
    branches: [ master ]
    paths: [ '.github/workflows/windows.yml', 'windows/**' ]

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  VCPKG_REPO: microsoft/vcpkg
  # 21.07.2025
  VCPKG_REF: b91c3336aee7f32412508f7dd351ae2cabdb8819

jobs:
  sdl2:
    strategy:
      matrix:
        arch: [x86, x64]
    name: Create SDL2 ${{ matrix.arch }} package
    runs-on: windows-2022
    timeout-minutes: 120
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v5
    - name: Create package directory
      run: |
        mkdir -p .output/sdl2
    - name: Prepare vcpkg cache
      uses: actions/cache@v4
      with:
        path: ~/AppData/Local/vcpkg/archives
        key: windows-sdl2-vcpkg-cache-${{ matrix.arch }}-${{ env.VCPKG_REF }}-${{ github.sha }}
        restore-keys: |
          windows-sdl2-vcpkg-cache-${{ matrix.arch }}-${{ env.VCPKG_REF }}-
          windows-sdl2-vcpkg-cache-${{ matrix.arch }}-
    - uses: actions/checkout@v5
      with:
        repository: ${{ env.VCPKG_REPO }}
        ref: ${{ env.VCPKG_REF }}
        path: .vcpkg
    - name: Apply vcpkg patches
      run: |
        for PATCH in windows/vcpkg_patches/*.patch; do
            if [[ -f "$PATCH" ]]; then
                patch -p1 -d .vcpkg < "$PATCH"
            fi
        done
    - name: Bootstrap vcpkg
      run: |
        .vcpkg/bootstrap-vcpkg.bat
    - name: Build
      run: |
        windows/sdl2.bat .vcpkg ${{ matrix.arch }} .output/sdl2
    - name: Get list of files installed by vcpkg
      if: ${{ github.event_name == 'pull_request' && ( success() || failure() ) }}
      run: |
        ls -lR .vcpkg/installed > .vcpkg/installed_files.txt
    - uses: actions/upload-artifact@v4
      if: ${{ github.event_name == 'pull_request' && ( success() || failure() ) }}
      with:
        name: sdl2-${{ matrix.arch }}-vcpkg-installed-files
        path: .vcpkg/installed_files.txt
    - uses: actions/upload-artifact@v4
      with:
        name: sdl2-${{ matrix.arch }}
        path: .output/sdl2
        if-no-files-found: error
  merge:
    name: Merge and upload package
    needs: [sdl2]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: sdl2-x86
        path: .output/sdl2
    - uses: actions/download-artifact@v4
      with:
        name: sdl2-x64
        path: .output/sdl2
    - uses: actions/upload-artifact@v4
      if: ${{ github.event_name == 'pull_request' }}
      with:
        name: windows
        path: .output
        if-no-files-found: error
        include-hidden-files: true
    - name: Create package archive
      if: ${{ github.event_name == 'push' }}
      run: |
        cd .output
        zip -r windows.zip sdl2
    - uses: ncipollo/release-action@v1
      if: ${{ github.event_name == 'push' }}
      with:
        artifacts: .output/windows.zip
        body: |
          `windows.zip` contains header files and libraries built in release and debug mode, as well as their PDB files
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Pre-built dependency package for building fheroes2 for Windows
        tag: windows-deps
        allowUpdates: true
        artifactErrorsFailBuild: true
        replacesArtifacts: true
