name: Windows

on:
  workflow_call:

env:
  VCPKG_REPO: oleg-derevenetz/vcpkg
  VCPKG_REF: sdl2-mixer-2.6.1

jobs:
  sdl1:
    name: Create SDL1 package
    runs-on: windows-2019
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Create a package directory
      run: |
        mkdir -p .packages/sdl1
    - name: Download dependencies
      run: |
        windows/sdl1.bat packages/windows .packages/sdl1
    - uses: actions/upload-artifact@v2
      with:
        name: sdl1
        path: .packages
  sdl2:
    strategy:
      matrix:
        arch: [x86, x64]
    name: Create SDL2 ${{ matrix.arch }} package
    runs-on: windows-2019
    timeout-minutes: 120
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Create a package directory
      run: |
        mkdir -p .packages/sdl2
    - name: Prepare vcpkg cache
      uses: actions/cache@v3
      with:
        path: ~/AppData/Local/vcpkg/archives
        key: windows-vcpkg-cache-${{ matrix.arch }}-${{ env.VCPKG_REF }}-${{ github.sha }}
        restore-keys: |
          windows-vcpkg-cache-${{ matrix.arch }}-${{ env.VCPKG_REF }}-
          windows-vcpkg-cache-${{ matrix.arch }}-
    - uses: actions/checkout@v3
      with:
        repository: ${{ env.VCPKG_REPO }}
        ref: ${{ env.VCPKG_REF }}
        path: .vcpkg
    - name: Bootstrap vcpkg
      run: |
        .vcpkg/bootstrap-vcpkg.bat
    - name: Build dependencies
      run: |
        windows/sdl2.bat .vcpkg ${{ matrix.arch }} .packages/sdl2
    - uses: actions/upload-artifact@v2
      with:
        name: sdl2-${{ matrix.arch }}
        path: .packages
  merge:
    name: Merge and upload package
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [sdl1, sdl2]
    steps:
    - name: Create a package directory
      run: |
        mkdir -p .packages
    - uses: actions/download-artifact@v2
      with:
        name: sdl1
        path: .packages
    - uses: actions/download-artifact@v2
      with:
        name: sdl2-x86
        path: .packages
    - uses: actions/download-artifact@v2
      with:
        name: sdl2-x64
        path: .packages
    - uses: actions/upload-artifact@v2
      if: ${{ github.event_name == 'pull_request' }}
      with:
        name: windows
        path: .packages
